urbanairship/react-native-airship

js/UrbanAirship.js

`UrbanAirship.removeListener` has a typo in the argument list (`handler` instead of `listener`), which causes the method to throw when used.
This PR fixes that issue, as well as improving the documentation for the method (no `EmitterSubscription` is returned by removeListener as far as I can see).

Make removeListener not crash (argument list typo)

---

android/src/main/AndroidManifest.xml
android/src/main/java/com/urbanairship/reactnative/CustomLandingPageActivity.java
android/src/main/java/com/urbanairship/reactnative/CustomMessageActivity.java
android/src/main/java/com/urbanairship/reactnative/CustomMessageCenterActivity.java
android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
ios/UARCTModule.xcodeproj/project.pbxproj
ios/UARCTModule/UARCTMessageViewController.h
ios/UARCTModule/UARCTMessageViewController.m
ios/UARCTModule/UrbanAirshipReactModule.m
js/UrbanAirship.js
sample/AirshipSample/app.js

Adds the ability to dismiss showing message center and message center messages. Dismissing message center is useful for apps that use the displayMessageCenter, while individual message dismissal is used for when an app displays their own message displaying.
On Android, its hard to access the activity stack in a clean non terrible way. Instead we will send an intent to the activities to close themselves. If the activity is currently running it will  receive the new intent through `onNewIntent`, if its not running it will just close itself immediately before its displayed to the user.

[MB-2246] Adds the ability to dismiss the default message center.

---

CHANGELOG.md
android/build.gradle
package.json
sample/AirshipSample/package.json

This is the react native release for version 1.2.0
It does the following things:
-Updates the Android SDK (the newest iOS SDK is auto selected by cocoapods)
-Add message center functionality for dismissing messages from outside the message center
-More responsive opt-in events

Release 1.2.0

---

android/src/main/java/com/urbanairship/reactnative/ReactAirshipPackage.java

ReactPackage.java does not have createJSModules anymore. Comment override annotation to support both RN >= 0.47 and RN < 0.47.

Fix Android package class to support RN 0.47

---

js/UrbanAirship.js

This PR fixes how setQuietTimeEnabled() and isQuietTimeEnabled() are set. Previously, these methods modified the values of user notifications (i.e. if quiet time was set to false then user notifications would get set to false):
```
/**
* Enables or disables quiet time.
*
* @param {boolean} enabled true to enable quiet time, false to disable.
*/
static setQuietTimeEnabled(enabled: boolean) {
UrbanAirshipModule.setUserNotificationsEnabled(enabled);
}
/**
* Checks if quietTime is enabled or not.
*
* @return {Promise.<boolean>} A promise with the result.
*/
static isQuietTimeEnabled(): Promise<boolean> {
return UrbanAirshipModule.isUserNotificationsEnabled();
}
```
Now these methods only modify the value of quiet time.

CE-3644: Fix quiet time methods in UrbanAirship.js

---

CHANGELOG.md
android/build.gradle
android/src/main/java/com/urbanairship/reactnative/ReactAirshipReceiver.java
android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.java
android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
android/src/main/java/com/urbanairship/reactnative/events/NotificationResponseEvent.java
android/src/main/java/com/urbanairship/reactnative/events/PushReceivedEvent.java
ios/UARCTModule/UARCTEventEmitter.h
ios/UARCTModule/UARCTEventEmitter.m
ios/UARCTModule/UrbanAirshipReactModule.m
js/UrbanAirship.js
package.json
sample/AirshipSample/android/app/build.gradle
sample/AirshipSample/android/build.gradle
sample/AirshipSample/android/gradle/wrapper/gradle-wrapper.properties

Adds support to clear and get active notifications. Adds 3 methods:
- getActiveNotifications: Returns the current notifications in the notification center
- clearNotifications: Clears all notifications for the app.
- clearNotification(identifier): Clears a specific notification.
Android notification Ids are a unique combination of a tag and int id. To normalize the API between iOS and Android, Android will expose the notification Id as "id:tag" and then parse it to do the actual clear.
https://github.com/urbanairship/react-native-module/issues/54

Add notification management support

---

CHANGELOG.md
ios/UARCTModule/UARCTMessageCenter.m
package.json
sample/AirshipSample/package.json

objectForKey was being used instead of boolForKey when checking the auto launch flag. Manually tested.

Release 1.3.1

---

CHANGELOG.md
ios/UARCTModule/UARCTAutopilot.m
ios/UARCTModule/UARCTMessageCenter.m
ios/UARCTModule/UrbanAirshipReactModule.m
package-lock.json
package.json
sample/AirshipSample/ios/Podfile.lock

Fixes an issue with iOS SDK 9.0 `deafultMessageCenter` => `messageCenter`. Tested on a simulator.

Release 1.4.1

---

android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.java
android/src/main/java/com/urbanairship/reactnative/events/PushReceivedEvent.java
android/src/main/java/com/urbanairship/reactnative/events/ShowInboxEvent.java
ios/UARCTModule/UARCTEventEmitter.h
ios/UARCTModule/UARCTEventEmitter.m
ios/UARCTModule/UARCTMessageCenter.m
js/UrbanAirship.js

Adds an event to show the inbox if auto launch message center is disabled. Needed to route all inbox events through the application if the app built an react native message center.
Testing:
- Verified it works on iOS and Android

[GH-73] Add show inbox event

---

android/src/main/java/com/urbanairship/reactnative/EventEmitter.java
android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
ios/UARCTModule/UARCTEventEmitter.m

This is cleaned up work from PR#90. 
- drops isCritical in Android
- adds functionality to only emit pending events when a matching listener is added in both iOS and Android

[MOBILE-179] Queue up push received and registration events

---

sample/AirshipSample/android/build.gradle

This fixes an error I was coming across when getting CI working. The ordering of the repositories matters here, for whatever reason. Also updated gradle build tools while I was at it.

[MOBILE-48] fix repo ordering, update gradle build tools

---

ReactNativeUAMigration.md

This is a small typo fix in React Native UA migration guide.

Fix: typo fix in migration guide

---

android/src/main/java/com/urbanairship/reactnative/Event.java
android/src/main/java/com/urbanairship/reactnative/EventEmitter.java
android/src/main/java/com/urbanairship/reactnative/ReactAirshipReceiver.java
android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.java
android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
android/src/main/java/com/urbanairship/reactnative/events/DeepLinkEvent.java
android/src/main/java/com/urbanairship/reactnative/events/InboxUpdatedEvent.java
android/src/main/java/com/urbanairship/reactnative/events/NotificationOptInEvent.java
android/src/main/java/com/urbanairship/reactnative/events/NotificationResponseEvent.java
android/src/main/java/com/urbanairship/reactnative/events/PushReceivedEvent.java
android/src/main/java/com/urbanairship/reactnative/events/RegistrationEvent.java
android/src/main/java/com/urbanairship/reactnative/events/ShowInboxEvent.java

Fixes a bug with pending events. The pending event check was only happening when redirecting `sendEvent` to the main looper. If it was called from the main thread it would not check to make sure we have a known listener for the event. I also went ahead and did some cleanup:
- removed the `isCritical` method from events (no longer used)
- simplify the reactContext lookup by having our module attach it to the event manager. No more casting :)
- instead of doing main looper checks, just post to the main thread
Fixes pending events on Android. 
Ran the sample app.

GH-148: Fix Android pending events

---

CHANGELOG.md
README.md
android/build.gradle
ios/UARCTModule/UARCTAutopilot.m
package-lock.json
package.json

Release 2.0.2.
Additional changes:
- Removed the gcm sender id from the README. Its optional now and we should pull it from the google-services.json by default.
- Android SDK to 9.5.0
- iOS SDK warning to 9.4.0

Release 2.0.2

---

ios/UARCTModule/UARCTEventEmitter.m

These changes fix the issue described in issue 23:
https://github.com/urbanairship/react-native-module/issues/23
More specifically, this changes the location of the known listener addition to before the pending events are sent in the addListener method. This matches the current Android functionality
These changes are necessary to allow the notification response to result in a notification to the js-bridge.
Ran the sample with and without change.

[GITHUB-23] fix listener addition in UARCTEventEmitter

---

android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
ios/UARCTModule/UrbanAirshipReactModule.m
js/UrbanAirship.js
js/index.d.ts
sample/AirshipSample/ios/Podfile
sample/AirshipSample/ios/Podfile.lock
sample/scripts/run_ci_tasks.sh

These changes provide an interface for the newly added enableUserPushNotifications function in UAPush. This allows users to enable push with a promise that returns the auth result.
Users want to be able to enable push and receive the authorization result back immediately. 
Manual testing in the sample.

[MOBILE-297] provide a way to enable notifications and get the auth result

---

CHANGELOG.md
android/build.gradle
package.json
sample/AirshipSample/package.json

This reverts the android-core dependency back to 16.0.1 due to a bug outlined here:
https://github.com/invertase/react-native-firebase/issues/1051 
To resolve android build issues outlined here:
https://github.com/urbanairship/react-native-module/issues/23
Ran Android sample, received push.

Release 2.1.1

---

android/build.gradle
package.json

Allow us to control the version of firebase core from our own projects' build.gradle files by adding a `safeExtGet` function
The fixed exact firebase version is causing conflicts with libraries that also require a fixed exact version of firebase-core
In my project-level build.gradle file I add the prop `firebaseCoreVersion` and define a version:
```
ext {
firebaseCoreVersion "+"
}
```
Or I do nothing and allow `safeExtGet` to fallback to the pre-defined version.
N/A

use safeExtGet to get android firebase-core

---

android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.java
ios/UARCTModule/UARCTAutopilot.m

This adds the ability to define custom notification categories by way of plist/xml files. I followed the approach used here https://github.com/urbanairship/urbanairship-cordova/pull/228
The main difference between cordova and react here is that there's no config.xml, and instead you have add files directly to an Xcode project or save them in res/xml. Otherwise it's the same pattern. Dev supplies `ua_custom_notification_buttons.xml` and/or `UACustomNotificationCategories.plist`, the plugin looks for these files after takeOff, and if present, uses them to load custom categories or button groups.
Tested manually. Docs PR can be found here: https://github.com/urbanairship/extdocs/pull/2833

[MOBILE-592] add support for custom notification categories

---

ios/UARCTModule/UrbanAirshipReactModule.m
sample/AirshipSample/ios/AirshipSample.xcodeproj/project.pbxproj
sample/AirshipSample/ios/Podfile
sample/AirshipSample/ios/Podfile.lock

There are two aspects of SDK 11.0 that required changes to the plugin. One was to get rid of old references to `[UAirship location]`. Instead of creating a whole separate plugin, this approach uses `[UAirship shared].locationProviderDelegate`, which calls through to the module (or a custom provider delegate) if present and no-ops otherwise. Since Airship dependencies are added using cocoapods, all a user has to do to enable the module is to add the AirshipLocationKit reference to their pod file. There will be other PRs in a bit that update the docs accordingly.
The other thing that needed work was methods having to do with display message center messages in overlays. We got rid of the old overlay controller in 11.0 (we hardly knew ye) and replaced it with a bridged HTML IAM. An …

MOBILE-642 Update react plugin to iOS SDK 11.0

---

MIGRATION.md

There is not much to migrate between the 2.x and 3.0 versions of our react native plugin. However, we should at least mention the change to how location is handled, and link to the appropriate section of the docs. There was no migration guide in the repo previously, so I created one.

[MOBILE-644] migration guide

---

android/src/main/java/com/urbanairship/reactnative/ReactAirshipPreferences.java
android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.java
android/src/main/java/com/urbanairship/reactnative/ReactNotificationProvider.java
android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
android/src/main/java/com/urbanairship/reactnative/Utils.java
js/UrbanAirship.js
js/index.d.ts

In order to provide an interface for configuring notification options, I roughly followed the approach already in place for the cordova plugin. The difference here is mostly in the way react native bridging works, the particulars of how preferences are dealt with at the plugin level, and the fact that  NotifiationFactory has been deprecated in favor of NotificationProvider as of SDK 10.

[MOBILE-403] ReactNotificationProvider, notification config support

---

android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.java

Part of the update to android SDK 10 means adding support for loading custom notification channels. The most straightforward way to do that is to follow the same approach as with notification button groups and provide a mechanism for loading custom notification channels from XML, which is what this does. We will also need to provide basic documentation on how to do this and what the XML structure looks like, which will come in a subsequent extdocs PR.

[MOBILE-401] add support for loading custom notification channels

---

android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
ios/UARCTModule/UrbanAirshipReactModule.m
js/UrbanAirship.js
js/index.d.ts

Adds support for delayed channel registration. To use delayed registration, you have to set `channelCreationDelayEnabled` to `YES`/`true` and then call `enableChannelCreation` on the push manager when you are ready to create a channel. This allows customers to delay when a billable user is created.
Customer request.
Manually tested it.

MOBILE-702: Add support for delayed channel registration

---

android/src/main/AndroidManifest.xml
android/src/main/java/com/urbanairship/reactnative/ReactAirshipPackage.java
android/src/main/java/com/urbanairship/reactnative/ReactMessageView.java
android/src/main/java/com/urbanairship/reactnative/ReactMessageViewManager.java
ios/UARCTModule/UARCTMessageView.h
ios/UARCTModule/UARCTMessageView.m
ios/UARCTModule/UARCTMessageViewManager.h
ios/UARCTModule/UARCTMessageViewManager.m
js/UAMessageView.js
js/index.js

Adds the ability to embed a message view in a react native context.
Makes building a custom message center possible.
I ran it on both iOS and Android and verified both are able to load messages, handle close, etc...

[MOBILE-571] ReactNative message view

---

android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
ios/UARCTModule/UrbanAirshipReactModule.m

Skips the message look up with a message is being displayed from an ID. The message views know how to handle refreshing the inbox if the message is not available.
Makes the API easier to use.
Manually tested both iOS and Android.

[MOBILE-809] Skip checking for message when displaying message with ID

---

example/ios/AirshipSample.xcodeproj/project.pbxproj
example/ios/AirshipSample/AirshipSample.entitlements
example/ios/AirshipSample/Images.xcassets/AppIcon.appiconset/Contents.json
example/ios/AirshipSample/Info.plist
example/ios/Podfile
example/ios/Podfile.lock
example/ios/ServiceExtension/Info.plist
example/ios/ServiceExtension/NotificationService.h
example/ios/ServiceExtension/NotificationService.m
example/ios/ServiceExtension/ServiceExtension.entitlements
package-lock.json
package.json

Re-add iOS notification service extension that was removed earlier in [this PR](https://github.com/urbanairship/react-native-module/pull/202).
We want to provide an example of how to provide a notification service extension.
Local build and run on both iOS and Android. Sent pushes to both. Used Inbox on both.
I had to upgrade to the most recent version of React in order to get support for `use_frameworks!` in CocoaPods. You'll see in `example/ios/Podfile` that I had to add a number of new Pods as a part of this change.
If you are interested in doing a commit-by-commit review, I broke up the work into the Cocoapods and then the Service Extension work.

[MOBILE-833] ReactNative: Add iOS notification service extension back into sample

---

.npmignore
js/__tests__/TagGroupEditor.test.js
js/__tests__/UACustomEvent.test.js
js/__tests__/UAEventEmitter.test.js
package-lock.json
package.json

The test framework I'm using here, jest, is developed by Facebook and is considered the de facto choice for react development. It's a little different from what we're used to, particularly where mocking is concerned (and especially when native modules are being used). I worked out some tests for UAEventEmitter, TagGroupEditor and UACustomEvent as an example of how to go about this for future enhancements. Tests can be run with a script by invoking `npm test`.
The main UrbanAirshipModule still needs tests but should be relatively straightforward with the existing ones as a guide. We should also be able to do some form of snapshot testing for the message view component, but it's not yet clear to me how much that will buy us, and it's an esoteric enough technique that we may as well save it …

MOBILE-807 react native testing

---

CHANGELOG.md
UrbanAirship-React-Native-Module.podspec
example/ios/AirshipSample.xcodeproj/project.pbxproj
example/ios/Podfile
example/ios/Podfile.lock
ios/UARCTModule/UARCTAutopilot.m
ios/UARCTModule/UARCTEventEmitter.m
ios/UARCTModule/UrbanAirshipReactModule.m
package-lock.json
package.json
scripts/run_ci_tasks.sh

This updates the module to use SDK 12.0, as well as fixing the inevitable deprecation warnings and some minor "recommending settings" Xcode stuff in the sample. More straightforward than the recent Cordova work, overall.
There were some things that were broken in the iOS section of the CI script that resulted in local build failures, so I went ahead and fixed those as well.

MOBILE-897 Update React Native module to SDK 12.0

---

ios/UARCTModule/UrbanAirshipReactModule.m
js/UrbanAirship.js

https://urbanairship.atlassian.net/browse/MOBILE-958
These changes add the ability to enable Autobadging in the React Native SDK.
Folks need a way to turn on Autobadging in this SDK just like the iOS SDK.
I called the methods from App.js in the example and made sure I could return the same boolean from isAutobadgeEnabled that I set in setAutobadgeEnabled. 
To reproduce:
1. Pull this branch and switch to it
2. Somewhere in App.js (I used the constructor), call setAutobadgeEnabled and pass in true.
3. Call isAutobadgeEnbled and add .then to the end, passing in a lambda function with an argument.
```
UrbanAirship.setAutobadgeEnabled(true);
UrbanAirship.isAutobadgeEnabled().then(result => console.log(result));
```
4. Print out the result and confirm that true is the boolean value returned.

[MOBILE-958] Added the ability to turn on Autobadging in React Native

---

android/build.gradle
android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
example/ios/Podfile.lock
ios/UARCTModule/UrbanAirshipReactModule.m
js/AttributeEditor.js
js/UrbanAirship.js

Add the ability to set attributes from react-native apps using the react-native-module.
To add attributes to iOS and Android via the react-native platfrom
Manual tested on iOS and Android
Manual testing Android:
https://slack-files.com/T025Q1VP7-FR6N38N75-b79d460d92
Manual testing iOS:

[MOBILE-1091] make react module attributes-compatible on ios and android

---

.npmignore
CHANGELOG.md
DEV_README.md
example/README.md
example/ios/Podfile.lock
ios/UARCTModule/UARCTModuleVersion.m
package-lock.json
package.json

Npm packages installed from a local source (i.e.`"file:../package/"` in the package.json) don't strip out files included in the .npmignore. This made my tests of the last plugin update unreliable. 
Includes the script/sync_version.sh script in the published npm package
Module install fails without the `sync_version.sh`script.
Ran `npm pack` and then checked the contents of the generated tarball to ensure the required script was in place.

Release 6.0.1

---

android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
ios/UARCTModule/UrbanAirshipReactModule.m
js/UrbanAirship.js

These changes expose the method trackScreen(screen) for the React Native Module
There was a Ticket on JIRA
For Android : Quickly added in the sample app a button that call the method, then changed screen and checked that in the logs the event was correctly tracked.
For iOS : I cannot test it since I don't have a Mac yet

[MOBILE-1268] Exposing trackScreen(screen) method

---

.github/workflows/release.yml
scripts/check_version.sh
scripts/upload_docs.sh

Uploads docs to GCS instead of mobile, adds a version check on the tag, and simplifies the release flow to be two parts (build/ci vs publish)
We want to remove the use of the mobile-docs repo

[MOBILE-1335] Simplify release workflow

---

CHANGELOG.md
DEV_README.md
example/ios/Podfile.lock
example/package.json
package.json
src/ios/UARCTModule/UARCTModuleVersion.m
src/package.json

Pretty self explanatory. This patch is mostly just to get rid of the unnecessary dependencies for the module, but it's also an opportunity to validate the new monorepo structure. I made a few edits to the dev readme and the scripts, as I discovered that the workspace structure we ended up with requires that you start metro from the repo root. There was also a cli-version script I had added, but that I don't think adds much value. If you're ever curious what version of the cli tools you have, just run `yarn react-native --version`.

[MOBILE-1336] update to 6.1.1

---

src/js/index.d.ts

This PR adds typescript definitions for ourUAMessageView, including typed interfaces for the properties and callback events. This makes it possible to instantiate a UAWebView like this:
```
<UAMessageView
style={{
height: 200,
}}
messageId="haha-not-a-real-message-YMMV"
onLoadStarted={(event: MessageLoadStartedEvent) => {
console.log("cool: " + event.messageId)
}}
onLoadError={(event: MessageLoadErrorEvent) => {
console.log("not cool: " + event.error)
}}>
</UAMessageView>
```
Here is a screenshot of the typescript app I hacked together to test it out:
We could stand to have better means of testing typescript stuff, so I'll probably be making a ticket or two to devote more time to creating a proper typescript example that we can continue to use going forward. It's a bit tricky with the new …

[MOBILE-831] add typescript definitions for UAMessageView

---

src/package.json
yarn.lock

There's a security vulnerability in acorn that was recently patched in 7.1.1.
https://snyk.io/vuln/SNYK-JS-ACORN-559469
We were originally notified by a Github bot, which automatically opened a PR of its own. Acorn is only a dev dependency, so this doesn't require republishing the plugin. I've manually verified that all the tooling still works properly.

[acorn-security-fix] update acorn to 7.1.1

---

src/ios/UARCTModule/UARCTAutopilot.m
src/ios/UARCTModule/UrbanAirshipReactModule.m

Remove [[NSUserDefaults standardUserDefaults] synchronize]. Apple recommends not using this method anymore

[MOBILE-978] Remove use of synchronize method

---

src/js/index.d.ts

Typescript definition file declares such component:
`UAMessageView extends React.Component`
but `React` type is not imported. Added it.
Missing import causes an error for Typescript compiler.
Typescript compiler passes correctly.
No need.
Would be nice to e.g. add a CI step to ensure that TS definition is valid in the future.

Add missing React import in TS definition

---

example/package.json
urbanairship-accengage-react-native/js/index.ts
urbanairship-hms-react-native/js/index.ts
urbanairship-location-react-native/ios/AirshipLocation.h
urbanairship-location-react-native/ios/AirshipLocation.m
urbanairship-location-react-native/ios/AirshipLocation.xcodeproj/project.pbxproj
urbanairship-location-react-native/ios/AirshipLocationReactModule.m

The accengage and HMS modules don't need to export anything in JS because they're just adding frameworks to the native build, and don't have anything to export. On iOS the location module was calling RCT_EXPORT_MODULE  from an empty class file, which was confusing React Native at runtime, with messages like "do you need to call RCT_EXPORT_MODULE?". I tested that the HMS module still gets loaded natively without anything being imported on the JS side, and that the location module is works on iOS as expected. Also bumped the version in the example, since we're now targeting 0.61.5.

[MOBILE-1729] fix exports for accengage, location, hms modules

---

urbanairship-react-native/js/UrbanAirship.ts

These changes change the `removeListener` method so that it takes an Event Emitter subscription to pass onto `removeSubscription` in `UAEventEmitter.ts`, which should remove the listener. I also added UAEventEmitter's `removeAllListeners` to `UrbanAirship.ts` as it wasn't previously in there, and should let users remove all event listeners of a certain type if they so choose.
`removeListener` doesn't work in its current state. I believe it's supposed to be inherited from React Native itself, but no combination of parameters actually seem to remove the listener (I've tried passing the event type as the first argument, and the emitter subscription as the second argument). From [this stack overflow question](https://stackoverflow.com/questions/36886628/how-do-you-remove-a-listener-from-react- …

[MOBILE 1797] Edited removeListener desciption, added removeAllListeners and removeSubscription methods

---

urbanairship-react-native/ios/UARCTModule/UARCTAutopilot.m

We were pulling presentation options in UARCTAutopilot using the KVC `valueForKey:` method instead of `integerForKey`. Casting this to an integer produces an integer of the backing object pointer, not the options integer its elf. As a result, any previously set foreground presentation options were getting overwritten with garbage during autopilot takeOff. This fixes the issue by checking to see if a value is actually stored in NSUserDefaults and if so, retrieving it using the correct method.
Tested manually on a device with foreground push notifications.

[MOBILE-1953] fix iOS foreground presentation options

---

example/ios/Podfile
example/ios/Podfile.lock
urbanairship-accengage-react-native/android/build.gradle
urbanairship-accengage-react-native/package.json
urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec
urbanairship-hms-react-native/android/build.gradle
urbanairship-hms-react-native/package.json
urbanairship-location-react-native/android/build.gradle
urbanairship-location-react-native/package.json
urbanairship-location-react-native/urbanairship-location-react-native.podspec
urbanairship-react-native/android/build.gradle
urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m
urbanairship-react-native/package.json
urbanairship-react-native/urbanairship-react-native.podspec

This updates both the android and SDKs to 14.0.1 and also includes an iOS fix for misinterpreted foreground notification options. Tested manually using the sample app.

[MOBILE-1955] release 9.0.1

---

CHANGELOG.md
README.md
example/ios/Podfile
example/ios/Podfile.lock
urbanairship-accengage-react-native/android/build.gradle
urbanairship-accengage-react-native/package.json
urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec
urbanairship-hms-react-native/android/build.gradle
urbanairship-hms-react-native/package.json
urbanairship-location-react-native/android/build.gradle
urbanairship-location-react-native/package.json
urbanairship-location-react-native/urbanairship-location-react-native.podspec
urbanairship-react-native/android/build.gradle
urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.java
urbanairship-react-native/ios/UARCTModule/UARCTAutopilot.m
urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m
urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m
urbanairship-react-native/js/UrbanAirship.ts
urbanairship-react-native/package.json
urbanairship-react-native/urbanairship-react-native.podspec

Release 10.0.0. I did a major release since we changed the type for InboxMessage extras as well as requiring Xcode 12.
I added some logging for SDK and module version, and fixed the logging for foreground presentation options to hopefully help debug https://github.com/urbanairship/react-native-module/issues/298

Release 10.0.0

---

urbanairship-react-native/ios/UARCTModule/UARCTAutopilot.h
urbanairship-react-native/ios/UARCTModule/UARCTAutopilot.m
urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m

Calls takeOff when the module is created. Left the NSNotificationCenter method in place in case the module is loaded at a later time after application:didFinishLaunching:

[MOBILE-2044] Ensure takeOff is called before accessing the module

---

CHANGELOG.md
example/ios/Podfile.lock
urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m
urbanairship-accengage-react-native/package.json
urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec
urbanairship-hms-react-native/package.json
urbanairship-location-react-native/ios/AirshipLocationReactModuleVersion.m
urbanairship-location-react-native/package.json
urbanairship-location-react-native/urbanairship-location-react-native.podspec
urbanairship-react-native/ios/UARCTModule/UARCTAutopilot.m
urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m
urbanairship-react-native/package.json
urbanairship-react-native/urbanairship-react-native.podspec

Update iOS SDK to 14.2.2 and React Native module to 10.0.2
To keep the React Native module updated
Manual tests
Some module versions values was not up to date since 8.1.0 but I think these are not used anyway.
Also, I base the changelog on iOS changelog. Feel free to send me some suggestions if that's not optimal.

[MOBILE-2059] Release 10.0.2

---

urbanairship-react-native/android/build.gradle
urbanairship-react-native/android/proguard-rules.pro
urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/AirshipExtender.java
urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.java
urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/ReactNotificationProvider.java

Adds a hook to customize airship before takeOff finishes so apps can set things like custom notification providers.
I tested this in the sample app with https://gist.github.com/rlepinski/d82229595538d897acc35fa294f35e3f

[MOBILE-2159] Make it possible to extend airship during takeoff

---

example/ios/Podfile.lock
urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec
urbanairship-hms-react-native/android/build.gradle
urbanairship-location-react-native/urbanairship-location-react-native.podspec
urbanairship-react-native/android/build.gradle
urbanairship-react-native/ios/UARCTModule/UARCTAutopilot.m
urbanairship-react-native/urbanairship-react-native.podspec

Update Android & iOS SDKs to 14.3.0
To keep the React Native module updated
Running the two sample apps and check that the SDK is correctly running

[MOBILE-2135] Update to latest SDKs in React Native

---

CHANGELOG.md
urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m
urbanairship-accengage-react-native/package.json
urbanairship-hms-react-native/package.json
urbanairship-location-react-native/ios/AirshipLocationReactModuleVersion.m
urbanairship-location-react-native/package.json
urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m
urbanairship-react-native/package.json

This release technically also supports React Native 0.6.4/React 17 but we don't need to call that out. Minimum requirements remain the same.

[MOBILE-2136] release 11.0

---

CHANGELOG.md
urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m
urbanairship-accengage-react-native/package.json
urbanairship-hms-react-native/package.json
urbanairship-location-react-native/ios/AirshipLocationReactModuleVersion.m
urbanairship-location-react-native/package.json
urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/events/NotificationResponseEvent.java
urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m
urbanairship-react-native/package.json

Fixes NPE regression introduced in 11.0.0. Reported here - https://github.com/urbanairship/react-native-module/issues/319
I verified the fix by opening a push on Android.

Release 11.0.1

---

example/ios/Podfile
example/ios/Podfile.lock
urbanairship-accengage-react-native/android/build.gradle
urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m
urbanairship-accengage-react-native/package.json
urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec
urbanairship-hms-react-native/android/build.gradle
urbanairship-hms-react-native/package.json
urbanairship-location-react-native/android/build.gradle
urbanairship-location-react-native/ios/AirshipLocationReactModuleVersion.m
urbanairship-location-react-native/package.json
urbanairship-location-react-native/urbanairship-location-react-native.podspec
urbanairship-react-native/android/build.gradle
urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m
urbanairship-react-native/package.json
urbanairship-react-native/urbanairship-react-native.podspec

Update the React Native plugin to 11.0.2, and the native SDKs version to 14.4.4 for Android, and 14.4.2 for iOS
To keep the SDKs up to date
By running the sample apps

[MOBILE-2357] Update React Module to SDKs 14.4.x

---

example/screens/MessageScreen.js

The loading indicator view in MessageScreen is blocking touches in our example code, even when it's not visible. This change makes sure that the view is only rendered if it is currently animating. Tested manually in the iOS simulator with the sample app, and verified that scrolling and buttons work as expected.

[MOBILE-2396] fix message view touch events in example

---

example/README.md

We still had a reference to `npm install` in the example README, which is confusing and results in errors. The example is connected to our yarn workspace, and so you have to use yarn to build the modules.

[MOBILE-2418] fix example README

---

example/ios/AirshipSample.xcodeproj/project.pbxproj
example/ios/AirshipSample.xcodeproj/xcshareddata/xcschemes/AirshipSample.xcscheme
example/ios/Podfile
example/ios/Podfile.lock
urbanairship-accengage-react-native/android/build.gradle
urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m
urbanairship-accengage-react-native/package.json
urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec
urbanairship-hms-react-native/android/build.gradle
urbanairship-hms-react-native/package.json
urbanairship-location-react-native/android/build.gradle
urbanairship-location-react-native/ios/AirshipLocationReactModuleVersion.m
urbanairship-location-react-native/package.json
urbanairship-location-react-native/urbanairship-location-react-native.podspec
urbanairship-react-native/android/build.gradle
urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m
urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m
urbanairship-react-native/js/UrbanAirship.ts
urbanairship-react-native/package.json
urbanairship-react-native/urbanairship-react-native.podspec

Updates the Airship SDKs version, expose the new privacy manager methods and remove the old data collection methods
To replace the data collection methods with the privacy manager
Tested the methods by logging the results in the sample.
The methods work fine on both Android and iOS.
We will need to add some example of use in the doc

[MOBILE-2359] Expose new privacy manager flags

---

.github/workflows/release.yml

Updates to the new modular GCP setup action.
So that deploys continue working.
Doing it live, but tested the new action in a private repo and it installed the GCP CLI utils without issue.

[MOBILE-2438] Update setup-cloud action in release workflow

---

urbanairship-react-native/js/MessageView.tsx

Adds missing type definition for prop messageId for MessageView

fix: Add missing prop type messageId for MessageView

---

urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m
urbanairship-react-native/js/UrbanAirship.ts

- Update the iOS method isUserNotificationsOptedIn to use the UAPush method. 
- Add a new method isSystemNotificationsEnabledForApp that checks for the notification manager on android and authorized types on iOS.
- Add another method that for Android getNotificationChannelStatus(channel) that returns enabled, disabled, and unknown where unknown is returned if it's not yet created.
Because this presents a problem for Axios React Native Implementation noted as the unified call essentially returns a different result between iOS and Android. Axios has built logic into their app that requires App-Level notification opt-in information that we currently do not expose for Android. 
Running with the sample app and testing the methods

[MOBILE-2482] isUserNotificationsOptedIn discrepancy between iOS and Android in React Native SDK Issue

---

CHANGELOG.md
example/ios/Podfile
example/ios/Podfile.lock
urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m
urbanairship-accengage-react-native/package.json
urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec
urbanairship-chat-react-native/package.json
urbanairship-chat-react-native/urbanairship-chat-react-native.podspec
urbanairship-hms-react-native/package.json
urbanairship-preference-center-react-native/package.json
urbanairship-preference-center-react-native/urbanairship-preference-center-react-native.podspec
urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m
urbanairship-react-native/package.json
urbanairship-react-native/urbanairship-react-native.podspec

Prep release 13.0.1
- Updated iOS SDK to `16.0.2`
- Updated iOS sample pods
- Changelog entry for `13.0.1`
Ran sample apps

[MOBILE-2633] Release 13.0.1

---

urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m

Fixes `isDeleted` on a message. A pointless flag since if they are deleted they no longer show up in the message list, but it should at least be accurate.

Fix isDeleted on iOS

---

urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m

Calls takeOff when the bridge is set to workaround the react view being displayed before applicationDidFinishLaunching. This should fix issue GH-371.

Call takeOff when bridge is set

---

urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m
urbanairship-react-native/js/SubscriptionLists.ts
urbanairship-react-native/js/UrbanAirship.ts
urbanairship-react-native/js/index.ts

Exposes subscription lists to react native. I set it up to make it easy to add contact lists once that is released in the SDK.
I tested by checking it rejects an empty list of types and calls back with the right results for the default value and [channel].

[MOBILE-2856] Expose subscription lists

---

urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java

Stub addListener and removeListeners methods
We need to stub the addListener and removeListeners methods in the react framework too to avoid these kind of warnings:
WARN new NativeEventEmitter() was called with a non-null argument without the required addListener method.
AirshipSample@http://10.0.2.2:8081/example/index.bundle?platform=android&dev=true&minify=false&app=com.urbanairship.sample&modulesOnly=false&runModule=true:110004:36
Tested it during MOBILE-2625 on our Gimbal adapter sample which had this issue

[MOBILE-2625-follow] Stub methods to fix react warning

---

urbanairship-react-native/ios/UARCTModule/UARCTUtils.m

Fix an issue with notification response callback not returning some information like title, subtitle and body.
We use extras dictionary instead of userInfo.
I used sample app

Fix notification response callback

---

urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m
urbanairship-react-native/js/UrbanAirship.ts

Adds method to expose `unreadMessagesCount` to React Native API
Closes #430 
Verified using the `example` app. If the user has any `unread` messages in the inbox, the function returns the correct value on both Platforms.

Get unread messages count

---

urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/ReactAirshipPreferences.java

With only the atomic boolean there are possibilities to have a null sharedPreferences.
We can keep the atomic boolean and add a null check to initialize the sharedPreferences.
Or we can remove the atomic boolean and just keep the null check.

[GHI-433] fix null preferences

---

urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/ReactMessageView.java

Fix a crash when trying to load a message with a poor connection
[This crash was ](https://github.com/urbanairship/react-native-module/issues/439)
Sample app
How to reproduce:
- Setup a poor network condition in the emulator.
- Comment out  
https://github.com/urbanairship/react-native-module/blob/1962b36cfa543810ba878d57e12478fcda3f1821/urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/ReactMessageView.java#L107
- Open a message from the message center and quit before the `onFinished` callback is called.

Fix a crash when trying to load a message with a poor connection

---

urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m
urbanairship-react-native/js/UrbanAirship.ts

Retargeted to a new `release-14.4.4` branch, off of `14.4.3`
* Fixes Android chat module version
* Adds support for configuring the IAA display interval at runtime
Feature request
- Confirmed the call made it to the native layers using the Android and iOS samples
- Ran tests

[MOBILE-3287] Expose IAA display interval

---

CHANGELOG.md
example/ios/Podfile.lock
urbanairship-accengage-react-native/android/build.gradle
urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m
urbanairship-accengage-react-native/package.json
urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec
urbanairship-chat-react-native/android/build.gradle
urbanairship-chat-react-native/package.json
urbanairship-chat-react-native/urbanairship-chat-react-native.podspec
urbanairship-hms-react-native/android/build.gradle
urbanairship-hms-react-native/package.json
urbanairship-preference-center-react-native/android/build.gradle
urbanairship-preference-center-react-native/package.json
urbanairship-preference-center-react-native/urbanairship-preference-center-react-native.podspec
urbanairship-react-native/android/build.gradle
urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m
urbanairship-react-native/package.json
urbanairship-react-native/urbanairship-react-native.podspec

Preps release 14.4.4:
- Add `UrbanAirship.setInAppAutomationDisplayInterval()` method
- Updated Airship Android SDK to 16.7.5
- Updated Airship iOS SDK to 16.9.4
:shipit: 
Ran Android and iOS samples

Release 14.4.4

---

urbanairship-react-native/ios/UARCTModule/UARCTMessageView.m

Prevents putting a nil in an objective-c dictionary.
Fix reported crash.

[GH-476] Protect against nil messageID

---

android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt
android/src/oldarch/java/com/urbanairship/reactnative/AirshipSpec.kt
ios/RTNAirship.mm
src/AirshipPreferenceCenter.ts
src/AirshipPush.ts
src/NativeRTNAirship.ts

Fixing type mismatches between the bindings. I went through and replaced `any` with `Spec` to see where it complained. I then reverted that change for now because the docs show to use `any`, but we should see if we can make this better going forward as its too easy to use a wrong method if we dont have type checks.

Fix up interface mismatch

---

ios/RTNAirship.mm
ios/RTNAirshipBootloader.m
ios/RTNAirshipMessageView.mm

Fixes an issue when iOS build would error when using Cocapods frameworks. I.e. setting the `use_frameworks` configuration.
Resolves issues #495 
To be able to use the `use_frameworks` to enable dynamic / static frameworks on iOS.
Tested running the example app with first installing the Podfile using:
```
NO_FLIPPER=1 USE_FRAMEWORKS="static" pod install
```
then building and running the example app using Xcode.

fix: Import when using cocapods frameworks

---

CHANGELOG.md
android/gradle.properties
package.json
react-native-airship.podspec

Updates the proxy library to remove usage of putIfAbsent so we can be backwards compatible with Android 23 and older.
https://github.com/Expensify/App/issues/17541

Release 15.2.3

---

CHANGELOG.md
android/src/main/java/com/urbanairship/reactnative/AirshipHeadlessEventService.kt
android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt
android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.kt
example/ios/Podfile.lock
package.json

When we switched to a turbo package, the module no longer initialized on app start, even if I set the flag to eagerInit. It still will wait for a react context. I had to move the event listener to start the headlessjs task in autopilot to work around this.

Release 15.2.6

---

CHANGELOG.md
MIGRATION.md
android/gradle.properties
android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt
android/src/main/java/com/urbanairship/reactnative/DataMigrator.kt
android/src/main/java/com/urbanairship/reactnative/Utils.kt
android/src/oldarch/java/com/urbanairship/reactnative/AirshipSpec.kt
example/ios/AirshipExample.xcodeproj/project.pbxproj
example/ios/AirshipExample/AppDelegate.mm
example/ios/AirshipExtender.swift
example/ios/Podfile
example/ios/Podfile.lock
example/src/App.tsx
example/src/screens/HomeScreen.tsx
ios/AirshipReactNative.swift
ios/MessageWebViewWrapper.swift
ios/RTNAirship.mm
package.json
react-native-airship.podspec
src/AirshipPush.ts
src/NativeRTNAirship.ts
src/types.ts

Waiting on iOS SDK 17.0.2 and then to bump the proxy version

Release 16.0.0

---

CHANGELOG.md
android/gradle.properties
example/ios/Podfile.lock
ios/AirshipReactNative.swift
package.json
react-native-airship.podspec

Patch release that updates the iOS and Android Airship SDK to 17.0.3.
- Updated iOS SDK to 17.0.3
- Updated Android SDK to 17.0.3
- Fixed Android HMS module version

Release 16.0.1

---

DEV_README.md
android/gradle.properties
android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt
android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.kt
example/README.md
example/ios/Podfile.lock
example/src/App.tsx
ios/AirshipReactNative.swift
ios/RTNAirship.mm
react-native-airship.podspec
src/AirshipChannel.ts
src/NativeRTNAirship.ts
src/TagEditor.ts

Add editTags method
To keep updated
Manual testing on the sample

[MOBILE-3865] Add editTags support

---

CHANGELOG.md
android/gradle.properties
android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt
android/src/oldarch/java/com/urbanairship/reactnative/AirshipSpec.kt
example/ios/Podfile.lock
ios/AirshipReactNative.swift
package.json
react-native-airship.podspec

This fixes an issue with channelEditTags for the old architecture.  When an interface is changed we have to manually update the old arch spec. 
I will add a follow up ticket to update the CI to build both arch types for Android and iOS to make sure we are not missing anything

Fix old architecture channelEditTags method

---

android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt

Fix the crash when using getActiveNotifications() on Android
Test on the sample app on Android and iOS

Crash when using Airship.push.getActiveNotifications()

---

android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt
android/src/oldarch/java/com/urbanairship/reactnative/AirshipSpec.kt
ios/RTNAirship.mm
src/AirshipChannel.ts
src/NativeRTNAirship.ts
src/types.ts

Add an enableChannelCreation method and mark it as deprecated along with the isChannelCreationDelayEnabled config.
To not block people that would still use the isChannelCreationDelayEnabled config.
Tested on iOS.
Android is working fine at APK.On my side, something with my environment is blocking for now, about CMake in the NDK...

[MOBILE-3980] Add enableChannelCreation method

---

CHANGELOG.md
android/gradle.properties
android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt
android/src/oldarch/java/com/urbanairship/reactnative/AirshipSpec.kt
example/ios/Podfile.lock
example/package-lock.json
example/package.json
ios/AirshipReactNative.swift
ios/RTNAirship.mm
package-lock.json
package.json
react-native-airship.podspec
src/AirshipContact.ts
src/NativeRTNAirship.ts

Minor release that updates the iOS SDK to 17.7.0 and Android SDK to 17.6.0 and adds support for notifying the contact of a remote login.
- Updated iOS SDK to 17.7.0
- Updated Android SDK to 17.6.0
- Added `Airship.contactManager.notifyRemoteLogin()` method to notify contact of remote login
🚀
Set breakpoints on notifyRemoteLogin in iOS and Android and ensured these got called when I called it:

Release 17.1.0

---

android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt

The `featureFlagManagerFlag` and `featureFlagManagerTrackInteraction` missed out the annotation to make it accessible from JS for Android native-module
Without this annotation, we can't use the `flag` and `trackInteraction` method on Android.
Added the annotation, rebuild the app, and verify that the method able to call the native method
Should fix https://github.com/urbanairship/react-native-airship/issues/540

fix(android): missing annotation on feature flag method

---

android/build.gradle

Check for the "airshipHmsEnabled" flag in ExtraProperties from build.gradle on android top level additionally to check in gradle.properties.
HMS requires "com.huawei.hms:push", which then requires the REQUEST_INSTALL_PACKAGES permission. This permission is considered as "high risk or sensitive permission" by Google (see https://support.google.com/googleplay/android-developer/answer/12085295?hl=en). 
Making the "airshipHmsEnabled" flag available in ExtraProperties of the root projects makes it easier to control wether HMS should be used or not in react native apps which are build for HarmonyOS and Android at the same time. By that we can avoid the whole "REQUEST_INSTALL_PACKAGES" mess in Playstore easier, because changing values in build.gradle files can be done with less effort.
Tested in …

Check ExtraProperties for "airshipHmsEnabled" additionally

---

.github/workflows/release.yml
CHANGELOG.md
android/gradle.properties
ios/AirshipReactNative.swift
package.json

Updates HMS version to 17.7.2
To match the SDK version
Build and run

Update hms version

---

src/types.ts

Fixes the listIconUrl definition to match the original specification and its comment. Will take a look to see if anything else needs updating.

Fix listIconUrl definition

---

CHANGELOG.md
example/ios/Podfile.lock

Release 18.0.1

---

CHANGELOG.md
android/gradle.properties
example/ios/Podfile.lock
ios/AirshipReactNative.swift
package.json
react-native-airship.podspec

updates the framework proxy
to get android's patch in
Build sample for android. Tested with APK for iOS.

Prepare release 19.2.0

---

ios/MessageWebViewWrapper.swift
src/types.ts

- Add a check in Message Center to allow the webview to be inspected in Safari
- Add a config field for isWebViewInspectionEnabled
To debug more easily the webviews
Putting isWebViewInspectionEnabled to true, running the sample app and inspecting the webview on Safari
To make testing faster and easier I edited the ProxyConfig so it loads the new field from the config, so I think it would be great to add it in the next Proxy update

[MOBILE-4628] Add Webview inspection check in MessageCenter

---

src/types.ts

In the issue $ https://github.com/Expensify/App/issues/46820, the push notification data attribute extra may have value of undefined
Better type definition could result in less bug.
Send push notification to app without payload.

Make JsonObject accept undefined value

---

.github/workflows/ci.yml
CHANGELOG.md
android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt
android/src/oldarch/java/com/urbanairship/reactnative/AirshipSpec.kt
example/ios/Podfile.lock
ios/AirshipReactNative.swift
package-lock.json
package.json

Adds missing methods in android old arch
to fix a compile error
Tested on an empty app with old arch and on Sample app with old arch.
Need a patch release

[MOBILE-4729] Add missing MC methods in android old arch

---

CHANGELOG.md
android/gradle.properties
android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt
example/ios/Podfile.lock
ios/AirshipReactNative.swift
package.json
react-native-airship.podspec

Fix live update and live activities on oldArch
bug fix for old architecture
sample app

fix live update and live activities on oldArch

---

CHANGELOG.md
android/gradle.properties
example/ios/Podfile.lock
ios/AirshipReactNative.swift
package.json
react-native-airship.podspec

Release 20.0.2

---

android/build.gradle

Synced the build.gradle file with a new module I generated.

Update build.gradle file

---

.github/workflows/prep-release.yml
scripts/update_changelog.sh
scripts/update_proxy_version.sh
scripts/update_version.sh

Release prep workflow and scripts

Add release preparation action and scripts

---

CHANGELOG.md
android/gradle.properties
example/ios/Podfile.lock
ios/AirshipReactNative.swift
package.json
react-native-airship.podspec

Bumps Android to 19.2.0 and iOS to 19.1.0
Fixing a prepare assets bug on Android that allows messages to be displayed even if we've failed to pre-cache an image asset.

Release 21.2.0

---

CHANGELOG.md
android/gradle.properties
example/ios/Podfile.lock
ios/AirshipReactNative.swift
package.json
react-native-airship.podspec

Backports the latest proxy (14.1.0) to 21.x for older React Native users.

Release 21.4.0

---

android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt
android/src/main/java/com/urbanairship/reactnative/ManifestUtils.kt
android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.kt

When disabling the headless task setup on start, nothing was adding it back when the module initialized causing an issue with push received.

Fix BG push when isHeadlessJSTaskEnabledOnStart is disabled

---

ios/RNAirshipMessageView.mm

The crash is in `React-Fabric: eventDispatche`r is a weak pointer, and for some reason the object it points to was already destroyed, so `.lock()` crashs.
Sample app

Resolve RNAirshipMessageViewEventEmitter crash
