urbanairship/react-native-airship

android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, ios/UARCTModule/UrbanAirshipReactModule.m, js/UrbanAirship.js
Adds the ability to set and get iOS badge counts.
=> [MB-2258] iOS Badging Support

android/src/main/java/com/urbanairship/reactnative/ReactAirshipPreferences.java, android/src/main/java/com/urbanairship/reactnative/ReactAirshipReceiver.java, android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
=> Channel reg callbacks emit opt status event on opt status change

README.md
Fixed a typo on a README link at the iOS Install section 👍
=> Fix README link format

android/src/main/java/com/urbanairship/reactnative/EventEmitter.java, android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, js/UAEventEmitter.js, js/UrbanAirship.js
Fixes issue #58 
Sends the addListener and removeListeners call to both iOS and Android so we know if we have a listener.
=> Fix delayed events on Android

CHANGELOG.md, android/build.gradle, ios/UARCTModule/UARCTAutopilot.m, ios/UARCTModule/UARCTMessageCenter.m, package-lock.json, package.json, sample/AirshipSample/ios/AirshipSample.xcodeproj/project.pbxproj, sample/AirshipSample/ios/Podfile, sample/AirshipSample/ios/Podfile.lock, sample/AirshipSample/package.json
-Updates current UA iOS SDK to 9.0.1 and Android SDK to 9.0.0
-Fixes deprecation warnings in iOS sample
-Applies suggested Xcode settings to iOS sample
-Updates podfile to list platform explicitly
=> Release 1.4.0

CHANGELOG.md, android/build.gradle, android/src/main/AndroidManifest.xml, package.json, sample/AirshipSample/android/app/src/main/AndroidManifest.xml, sample/AirshipSample/android/build.gradle, sample/AirshipSample/app.js, sample/AirshipSample/package.json
Fixes issues with Android 9.0 SDK.
Testing:
- Sent push with landing page, everything worked
- Launched message center
- Added a tag
=> Release 1.4.2

android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, ios/UARCTModule/UrbanAirshipReactModule.m, js/UrbanAirship.js
Adds a method to get the registration token
=> [GH-79] Expose method to get the registration token

android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
Matches the iOS implementation.
=> [GH-82] Allow clearing named user with an empty string

CHANGELOG.md, android/build.gradle, ios/UARCTModule/UARCTAutopilot.m, package.json, sample/AirshipSample/package.json
=> Release 1.5.0

ios/UARCTModule/UARCTAutopilot.h, ios/UARCTModule/UARCTAutopilot.m
Needed by a user who is trying disable react at runtime for iPad devices.
=> [CUSTENG-37] Add flag to disable react integration at runtime

js/index.d.ts, package.json
This PR adds a TS definitions file
=> Add Typescript definitions

CHANGELOG.md, android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, package-lock.json, sample/AirshipSample/android/app/build.gradle, sample/AirshipSample/android/build.gradle, sample/AirshipSample/android/gradle/wrapper/gradle-wrapper.properties
https://github.com/urbanairship/react-native-module/issues/110
=> Release 1.6.2

android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, ios/UARCTModule/UrbanAirshipReactModule.m, js/TagGroupEditor.js, js/index.d.ts
Adding support for setTags for iOS and Android for Channel and Named User Tag Groups
=> Added SetTag operation to TagGroupEditor

ios/UARCTModule.xcodeproj/xcshareddata/xcschemes/UARCTModule.xcscheme
Adds shared scheme for use with continuous integration.
=> Share UARCTModule scheme for ci

DEV_README.md, README.md, android/build.gradle, sample/AirshipSample/android/app/build.gradle, sample/AirshipSample/android/build.gradle
- Adds dependencies for FCM support
- Updates Android AirshipSample to use FCM (adds the necessary gradle plugin dependency)
- Updates README with FCM setup documentation
=> [MOBILE-208] update dependencies for FCM support

CHANGELOG.md, package.json, sample/AirshipSample/package.json
Change version numbers to 2.0.1 and update changelog.
Release version 2.0.1
=> Version 2.0.1

CHANGELOG.md, README.md, android/build.gradle, ios/UARCTModule/UARCTAutopilot.m, package.json, sample/AirshipSample/package.json
Release 2.1.0
Building both samples (iOS manually, Android via CI)
=> Release 2.1.0

README.md, js/UrbanAirship.js, js/index.d.ts
Adds more docs around registration tokens and push notifications. See GH-158
=> [GH-158] Add more docs around the registration token

CHANGELOG.md, android/build.gradle, ios/UARCTModule/UARCTAutopilot.m, package.json, sample/AirshipSample/android/app/build.gradle, sample/AirshipSample/android/app/src/main/AndroidManifest.xml, sample/AirshipSample/android/build.gradle, sample/AirshipSample/android/gradle/wrapper/gradle-wrapper.properties, sample/AirshipSample/ios/Podfile.lock, sample/AirshipSample/package.json
Update iOS and Android UA-lib dependencies, updates some Android dependencies to allow the sample to build properly.
Keep things fresh.
Ran both iOS and Android samples.
=> Release 2.1.2

js/UrbanAirship.js
Fix docs problem by removing `@param` for non-existent param.
Docs need to be accurate.
Built docs locally.
=> [MOBILE-405] Fix docs

CHANGELOG.md, DEV_README.md, README.md, android/build.gradle, package-lock.json, package.json, sample/AirshipSample/android/build.gradle
Release 2.2.0:
- Updated Android SDK to 9.6.0
- Made the compile and target SDK version set to 28
- Updated sample with the new requirements
- Added section on overriding the dependency versions
=> Release 2.2.0

android/src/main/java/com/urbanairship/reactnative/CustomLandingPageActivity.java, android/src/main/java/com/urbanairship/reactnative/CustomMessageActivity.java, android/src/main/java/com/urbanairship/reactnative/CustomMessageCenterActivity.java, android/src/main/java/com/urbanairship/reactnative/Event.java, android/src/main/java/com/urbanairship/reactnative/EventEmitter.java, android/src/main/java/com/urbanairship/reactnative/ReactAirshipPackage.java, android/src/main/java/com/urbanairship/reactnative/ReactAirshipPreferences.java, android/src/main/java/com/urbanairship/reactnative/ReactAirshipReceiver.java, android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.java, android/src/main/java/com/urbanairship/reactnative/RequestPermissionsTask.java, android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, android/src/main/java/com/urbanairship/reactnative/events/DeepLinkEvent.java, android/src/main/java/com/urbanairship/reactnative/events/InboxUpdatedEvent.java, android/src/main/java/com/urbanairship/reactnative/events/NotificationOptInEvent.java, android/src/main/java/com/urbanairship/reactnative/events/NotificationResponseEvent.java, android/src/main/java/com/urbanairship/reactnative/events/PushReceivedEvent.java, android/src/main/java/com/urbanairship/reactnative/events/RegistrationEvent.java, android/src/main/java/com/urbanairship/reactnative/events/ShowInboxEvent.java, ios/UARCTModule/UARCTAutopilot.h, ios/UARCTModule/UARCTAutopilot.m, ios/UARCTModule/UARCTDeepLinkAction.h, ios/UARCTModule/UARCTDeepLinkAction.m, ios/UARCTModule/UARCTEventEmitter.h, ios/UARCTModule/UARCTEventEmitter.m, ios/UARCTModule/UARCTMessageCenter.h, ios/UARCTModule/UARCTMessageCenter.m, ios/UARCTModule/UARCTMessageViewController.h, ios/UARCTModule/UARCTMessageViewController.m, ios/UARCTModule/UrbanAirshipReactModule.h, ios/UARCTModule/UrbanAirshipReactModule.m
Remove date ranges from copyrights
To avoid needing to update the copyrights each year.
=> [MOBILE-462] remove copyright date ranges

CHANGELOG.md, android/build.gradle, package.json
=> Release 2.2.1

js/UrbanAirship.js
The APIs are remaining the same so there's not much to update, but I thought it would be good to let users know that there are extra steps for supporting location now, and to link to that area of the docs. The link exists only in my imagination but I'll have a separate PR up soon for actually making it real.
=> [MOBILE-646] update location related API docs

UrbanAirship-React-Native-Module.podspec, package.json
Adds a podspec that matches the naming convention followed by our other cocoapods. 
To simplify the integration.
Installed pod locally.
=> [MOBILE-693] add podspec

CHANGELOG.md, package.json
Fixes package issue due to a bug in npm  - https://github.com/npm/npm-packlist/commit/68b7c96
Need to publish with npm >= 6.10 to fix the issue
=> Release 3.1.1

CHANGELOG.md, ios/UARCTModule/UrbanAirshipReactModule.m, js/UrbanAirship.js, package-lock.json, package.json
Fixes GH-196 & GH-197
I also totally messed up the changelog somehow in the past release.
=> Release 3.1.2

android/src/main/java/com/urbanairship/reactnative/ReactMessageView.java, ios/UARCTModule/UARCTMessageView.m
Make the new message view events use `messageId` to match the `showInbox` event.
=> Match showInbox event

CHANGELOG.md, UrbanAirship-React-Native-Module.podspec, android/build.gradle, android/src/main/AndroidManifest.xml, android/src/main/java/com/urbanairship/reactnative/ReactAirshipPackage.java, android/src/main/java/com/urbanairship/reactnative/ReactMessageView.java, android/src/main/java/com/urbanairship/reactnative/ReactMessageViewManager.java, android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, ios/UARCTModule/UARCTAutopilot.m, ios/UARCTModule/UARCTMessageView.h, ios/UARCTModule/UARCTMessageView.m, ios/UARCTModule/UARCTMessageViewManager.h, ios/UARCTModule/UARCTMessageViewManager.m, ios/UARCTModule/UrbanAirshipReactModule.m, js/UAMessageView.js, js/index.js, package-lock.json, package.json
Release 3.2.0. Will follow up with a 4.0.0 release for AndroidX and ReactNative 0.6
Only take a look at the changelog, that really is the only new thing. Everything else is from the 4.0 branch. CI is going to fail because its setup for the 4.0 branch
=> Release 3.2.0

CHANGELOG.md, android/src/main/java/com/urbanairship/reactnative/ReactMessageViewManager.java, package.json
Release 4.0.0 for reactnative .6
=> Release 4.0.0

CHANGELOG.md, android/build.gradle, android/src/main/java/com/urbanairship/reactnative/ReactMessageView.java, android/src/main/java/com/urbanairship/reactnative/ReactMessageViewManager.java, ios/UARCTModule.xcodeproj/project.pbxproj, package.json
Fixes GH-212. The main issue seemed to be embedding a webview directly in a react view stack. IU was able to work around the issue by wrapping the UAWebView in a framelayout. Also added missing files to the xcode project on iOS.
=> Release 3.2.2

DEV_README.md
fixes the properties file path
=> fix properties file path

android/src/main/java/com/urbanairship/reactnative/ReactMessageView.java
Theses changes fix a bug in the ReactMessageView class, where the variable "message" was re-created.
To fix an issue.
I sent a message to my device, and checked if everything is displaying correctly and that there is no crash.
=> [MOBILE-1006] Fixing MessageView callbacks

CHANGELOG.md, UrbanAirship-React-Native-Module.podspec, package-lock.json, package.json
=> Release 5.0.1

UrbanAirship-React-Native-Module.podspec, android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, example/ios/AirshipSample.xcodeproj/project.pbxproj, example/ios/AirshipSample.xcodeproj/xcshareddata/xcschemes/AirshipSample.xcscheme, example/ios/Podfile.lock, ios/UARCTModule/UARCTAutopilot.h, ios/UARCTModule/UARCTAutopilot.m, ios/UARCTModule/UARCTDeepLinkAction.h, ios/UARCTModule/UARCTEventEmitter.h, ios/UARCTModule/UARCTEventEmitter.m, ios/UARCTModule/UARCTMessageCenter.h, ios/UARCTModule/UARCTMessageCenter.m, ios/UARCTModule/UARCTMessageView.h, ios/UARCTModule/UARCTMessageView.m, ios/UARCTModule/UARCTMessageViewController.h, ios/UARCTModule/UARCTMessageViewManager.h, ios/UARCTModule/UrbanAirshipReactModule.h, ios/UARCTModule/UrbanAirshipReactModule.m, js/UrbanAirship.js, js/index.d.ts
Updates the react-native plugin to iOS SDK 13.0.1
Migrates the plugin to work with iOS SDK 13.0.1
Manual testing with the sample.
Tested inbox action, open inbox, opening messages, various other actions including landing pages just because.
=> [MOBILE-1044] update iOS to SDK 13.0.1

LICENSE, README.md, UrbanAirship-React-Native-Module.podspec, android/build.gradle, android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, example/ios/Podfile.lock, ios/UARCTModule.xcodeproj/project.pbxproj, ios/UARCTModule/UARCTAutopilot.m, ios/UARCTModule/UARCTModuleVersion.h, ios/UARCTModule/UARCTModuleVersion.m, package.json, scripts/sync_version.sh
Adds module tracking to ios and android and does some cleanup for the release
=> [MOBILE-1131] add module version tracking to ios and android

UrbanAirship-React-Native-Module.podspec, example/ios/Podfile.lock, ios/UARCTModule/UARCTAutopilot.m
Updates React Native to iOS SDK 13.1
=> [MOBILE-1276] Update iOS to 13.1

android/build.gradle
Upgrading the Android SDK version of the React Native Module from 12.1.0 to 12.2.0
To keep the latest version
By running the sample app and check that the correct version is loaded
No
=> [MOBILE-1275] Upgrading Android SDK Version

android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, ios/UARCTModule/UrbanAirshipReactModule.m, js/UrbanAirship.js
Adds data collection and push token registration flags to react native.
Manually tested in the sample app.
=> [MOBILE-1271] Add data collection flag

android/build.gradle, android/src/main/java/com/urbanairship/reactnative/CustomMessageActivity.java, android/src/main/java/com/urbanairship/reactnative/CustomMessageCenterActivity.java, android/src/main/java/com/urbanairship/reactnative/Event.java, android/src/main/java/com/urbanairship/reactnative/EventEmitter.java, android/src/main/java/com/urbanairship/reactnative/PluginLogger.java, android/src/main/java/com/urbanairship/reactnative/ReactAirshipPackage.java, android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.java, android/src/main/java/com/urbanairship/reactnative/ReactMessageView.java, android/src/main/java/com/urbanairship/reactnative/ReactMessageViewManager.java, android/src/main/java/com/urbanairship/reactnative/ReactNotificationProvider.java, android/src/main/java/com/urbanairship/reactnative/RequestPermissionsTask.java, android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, android/src/main/java/com/urbanairship/reactnative/Utils.java, android/src/main/java/com/urbanairship/reactnative/events/DeepLinkEvent.java, android/src/main/java/com/urbanairship/reactnative/events/NotificationResponseEvent.java, android/src/main/java/com/urbanairship/reactnative/events/PushReceivedEvent.java, android/src/main/java/com/urbanairship/reactnative/events/RegistrationEvent.java, js/UrbanAirship.js
Fixes an unchecked cast warning and deprecated api usage warnings during build. I also went through the code check in Android studio and fixed most the issues and lint issues.
Prevents build warnings.
Built the sample.
=> [GH-250] Fix unchecked build warning

.github/workflows/release.yml, CHANGELOG.md
Adds creating a github release during our release flow. Reformats the changelog to make it easier to pull the release notes.
=> [MOBILE-1345] Add github releases

CHANGELOG.md, src/android/build.gradle, src/ios/UARCTModule/UARCTModuleVersion.m, src/package.json
=> Release 6.1.2

CHANGELOG.md, example/ios/Podfile.lock, src/ios/UARCTModule/UARCTAutopilot.m, src/ios/UARCTModule/UARCTModuleVersion.m, src/package.json, src/urbanairship-react-native.podspec
=> Release 6.1.3

example/App.js, example/Styles.js, example/ios/AirshipSample.xcodeproj/project.pbxproj, example/ios/Podfile.lock, example/package.json, example/screens/MessageCenterScreen.js, example/screens/MessageScreen.js, example/screens/SettingsScreen.js, yarn.lock
Add a message center screen to the ReactNative sample app.
Using the sample app.
I tried hard to display the message center embedded in the navigation tab but I did not succeed.
If anyone know how to do it, I want really to improve it.
=> [MOBILE-1165] - Add a message center screen to the ReactNative sample app

example/App.js, example/Styles.js, example/index.js, example/screens/HomeScreen.js, example/screens/MessageCenterScreen.js, example/screens/MessageScreen.js, example/screens/SettingsScreen.js, src/js/AttributeEditor.js, src/js/TagGroupEditor.js, src/js/UACustomEvent.js, src/js/UAEventEmitter.js, src/js/UrbanAirship.js, src/js/index.js
=> [MOBILE-1425] - Add Airship copyrights

example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties, src/android/build.gradle, src/android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.java, src/android/src/main/java/com/urbanairship/reactnative/ReactMessageView.java, src/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
All pretty straightforward changes related to SDK 13 and modularization. I updated the gradle tooling in AS at its behest, but I ended up rolling back the gradle plugin version to the next most recent (3.5.4) to avoid the NDK bug currently affecting 3.6.x.
Tested manually in the example app.
=> MOBILE-1585 update android SDK to 13.1.0

example/ios/Podfile.lock, src/ios/UARCTModule/UARCTAutopilot.m, src/ios/UARCTModule/UARCTMessageViewController.h, src/ios/UARCTModule/UARCTMessageViewController.m, src/ios/UARCTModule/UrbanAirshipReactModule.m, src/urbanairship-react-native.podspec
Update React Native to iOS SDK 13.3.0
=> Mobile 1533 - Update React Native to iOS SDK 13.3.0

src/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, src/ios/UARCTModule/UrbanAirshipReactModule.m, src/js/UrbanAirship.js
Add names user attributes support.
Ti allow customers using React Native to use this feature.
Manual tests in sample apps.
=> [MOBILE-1567] Named user attributes

src/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, src/ios/UARCTModule/UrbanAirshipReactModule.m, src/js/AttributeEditor.js
Add date attributes support to React Native
Using the sample App.
PS: Need a rebase after merging the [268 PR](https://github.com/urbanairship/react-native-module/pull/268 ) to fix the github-actions CI / ios job. 
Update:
=> [Mobile 1531] - Add date attributes support to React Native

src/js/AttributeEditor.js, src/js/UrbanAirship.js, src/js/index.d.ts
This ticket was originally to add typescript definitions for the data collection methods, but I did an audit and found we were missing several other things. I also cleaned up some problematic parts of the documentation in both TS and JS. We will want to take extra care to make sure that the new additions in other recent tickets are updated in in index.d.ts.
Tested manually with a bespoke typescript app.
=> [MOBILE-1585-ts] update typescript definitions, fix jsdoc

DEV_README.md, src/js/UACustomEvent.js, src/js/__tests__/UACustomEvent.test.js, src/js/index.d.ts
Allow custom events to accept any JSON.
Events need JSON.
Unit tests. Local testing using modified sample app.
I was pleasantly surprised that everything _just worked_ once I extend the method signatures.
=> [MOBILE-1564] Remove property restrictions for custom events

CHANGELOG.md, example/ios/Podfile.lock, package.json, src/android/build.gradle, src/ios/UARCTModule/UARCTAutopilot.m, src/urbanairship-react-native.podspec, yarn.lock
Release 7.0.0
New features, new SDK versions
Local builds, local test on iOS & Android devices.
=> [MOBILE-1589] Release 7.0.0

CHANGELOG.md, MIGRATION.md, common-build.gradle, example/ios/Podfile.lock, urbanairship-accengage-react-native/package.json, urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec, urbanairship-hms-react-native/package.json, urbanairship-location-react-native/package.json, urbanairship-location-react-native/urbanairship-location-react-native.podspec, urbanairship-react-native/ios/UARCTModule/UARCTAutopilot.m, urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m, urbanairship-react-native/js/MessageView.tsx, urbanairship-react-native/package.json, urbanairship-react-native/urbanairship-react-native.podspec
Something that we want to get in before actually releasing 8.0.0. The majority of the changes are typescript related, but there were a few additions and removals. I also fixed a typo in MessageView.
=> [MOBILE-1737] Release 8.0.0

.github/workflows/release.yml, urbanairship-location-react-native/android/build.gradle
Adds the new modules to our publishing workflow, and also removes an unneeded airshipVersion re-definition that was out of date.
=> [fix-publishing] publish new modules

CHANGELOG.md, example/ios/Podfile.lock, urbanairship-accengage-react-native/android/build.gradle, urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m, urbanairship-accengage-react-native/package.json, urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec, urbanairship-hms-react-native/android/build.gradle, urbanairship-hms-react-native/package.json, urbanairship-location-react-native/android/build.gradle, urbanairship-location-react-native/ios/AirshipLocationReactModuleVersion.m, urbanairship-location-react-native/package.json, urbanairship-location-react-native/urbanairship-location-react-native.podspec, urbanairship-react-native/android/build.gradle, urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m, urbanairship-react-native/package.json, urbanairship-react-native/scripts/sync_version.sh, urbanairship-react-native/urbanairship-react-native.podspec
Release 8.0.1
Tested install on a fresh app referencing the packaged modules (Airship and AirshipLocation)
=> Release 8.0.1

CHANGELOG.md, example/README.md, example/ios/Podfile.lock, urbanairship-accengage-react-native/android/build.gradle, urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m, urbanairship-accengage-react-native/package.json, urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec, urbanairship-hms-react-native/android/build.gradle, urbanairship-hms-react-native/package.json, urbanairship-location-react-native/android/build.gradle, urbanairship-location-react-native/android/src/main/java/com/urbanairship/reactnative/location/AirshipLocationReactModule.java, urbanairship-location-react-native/ios/AirshipLocationReactModuleVersion.m, urbanairship-location-react-native/js/AirshipLocation.ts, urbanairship-location-react-native/package.json, urbanairship-location-react-native/urbanairship-location-react-native.podspec, urbanairship-react-native/android/build.gradle, urbanairship-react-native/ios/UARCTModule/UARCTAutopilot.m, urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m, urbanairship-react-native/package.json, urbanairship-react-native/urbanairship-react-native.podspec
Update iOS 13.5.4 & Android 13.3.2. Release react-native-module version 8.1.0.
Get fixes and improvements to our framework customers.
Local and Github CI. Received push iOS and Android Sample apps.
=> [MOBILE-1818] Release React Native 8.1.0

CHANGELOG.md, example/ios/Podfile, example/ios/Podfile.lock, urbanairship-accengage-react-native/android/build.gradle, urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m, urbanairship-accengage-react-native/package.json, urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec, urbanairship-chat-react-native/android/build.gradle, urbanairship-chat-react-native/package.json, urbanairship-chat-react-native/urbanairship-chat-react-native.podspec, urbanairship-hms-react-native/android/build.gradle, urbanairship-hms-react-native/package.json, urbanairship-preference-center-react-native/android/build.gradle, urbanairship-preference-center-react-native/package.json, urbanairship-preference-center-react-native/urbanairship-preference-center-react-native.podspec, urbanairship-react-native/android/build.gradle, urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, urbanairship-react-native/ios/UARCTModule/UARCTEventEmitter.m, urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m, urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m, urbanairship-react-native/package.json, urbanairship-react-native/urbanairship-react-native.podspec
Fixes a bunch of issues with 13.x and updates to latest SDKs
=> Release 13.0.2

CHANGELOG.md, example/ios/Podfile, example/ios/Podfile.lock, urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m, urbanairship-accengage-react-native/package.json, urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec, urbanairship-chat-react-native/package.json, urbanairship-chat-react-native/urbanairship-chat-react-native.podspec, urbanairship-hms-react-native/package.json, urbanairship-preference-center-react-native/package.json, urbanairship-preference-center-react-native/urbanairship-preference-center-react-native.podspec, urbanairship-react-native/ios/UARCTModule/UARCTEventEmitter.m, urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m, urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m, urbanairship-react-native/package.json, urbanairship-react-native/urbanairship-react-native.podspec, yarn.lock
Updates to latest iOS Airship SDKs 16.1.1
running sample app
=> [MOBILE-2713]-Update react native to latest iOS version 16.1.1

urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m
Make the setAnalyticsEnabled method work again
To avoid crashes on iOS
Manual tests
=> [MOBILE-272] Make setAnalyticsEnabled work again

urbanairship-preference-center-react-native/android/src/main/java/com/urbanairship/reactnative/preferenceCenter/AirshipPreferenceCenterModule.java, urbanairship-preference-center-react-native/ios/AirshipPreferenceCenterModule.m, urbanairship-preference-center-react-native/js/AirshipPreferenceCenter.ts
Add missing subscriptioId to preference center config section item
=> App subscriptionId to the preference center config section item

CHANGELOG.md, example/ios/Podfile, example/ios/Podfile.lock, urbanairship-accengage-react-native/android/build.gradle, urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m, urbanairship-accengage-react-native/package.json, urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec, urbanairship-chat-react-native/android/build.gradle, urbanairship-chat-react-native/package.json, urbanairship-chat-react-native/urbanairship-chat-react-native.podspec, urbanairship-hms-react-native/android/build.gradle, urbanairship-hms-react-native/package.json, urbanairship-preference-center-react-native/android/build.gradle, urbanairship-preference-center-react-native/package.json, urbanairship-preference-center-react-native/urbanairship-preference-center-react-native.podspec, urbanairship-react-native/android/build.gradle, urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m, urbanairship-react-native/package.json, urbanairship-react-native/urbanairship-react-native.podspec
=> Release React native 13.1.1

example/android/app/src/main/AndroidManifest.xml, example/ios/Podfile, example/ios/Podfile.lock, urbanairship-accengage-react-native/android/build.gradle, urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec, urbanairship-chat-react-native/android/build.gradle, urbanairship-chat-react-native/urbanairship-chat-react-native.podspec, urbanairship-hms-react-native/android/build.gradle, urbanairship-preference-center-react-native/android/build.gradle, urbanairship-preference-center-react-native/urbanairship-preference-center-react-native.podspec, urbanairship-react-native/android/build.gradle, urbanairship-react-native/urbanairship-react-native.podspec, yarn.lock
Updates to latest SDKs, had to do a minor change to the manifest for Android S on the sample app.
=> [MOBILE-2855] Update the SDK to 16.2.0

urbanairship-preference-center-react-native/android/src/main/java/com/urbanairship/reactnative/preferenceCenter/AirshipPreferenceCenterModule.java, urbanairship-preference-center-react-native/ios/AirshipPreferenceCenterModule.m, urbanairship-preference-center-react-native/js/AirshipPreferenceCenter.ts
Fixes the preference center config to return the items under the right key (matching the typescript).
=> [MOBILE-2854] Item -> Items to match TS

CHANGELOG.md, urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m, urbanairship-accengage-react-native/package.json, urbanairship-chat-react-native/package.json, urbanairship-hms-react-native/package.json, urbanairship-preference-center-react-native/package.json, urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m, urbanairship-react-native/package.json
=> Release 13.2.0

CHANGELOG.md, urbanairship-accengage-react-native/android/build.gradle, urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m, urbanairship-accengage-react-native/package.json, urbanairship-chat-react-native/android/build.gradle, urbanairship-chat-react-native/package.json, urbanairship-hms-react-native/package.json, urbanairship-preference-center-react-native/android/build.gradle, urbanairship-preference-center-react-native/package.json, urbanairship-react-native/android/build.gradle, urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m, urbanairship-react-native/package.json
Excludes appcompat from our dependencies to avoid RN crash
=> Patch release 13.2.1

urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/ReactAirshipPreferences.java, urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.java, urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/ReactNotificationProvider.java, urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/Utils.java, urbanairship-react-native/ios/UARCTModule/UARCTAutopilot.h, urbanairship-react-native/ios/UARCTModule/UARCTAutopilot.m, urbanairship-react-native/ios/UARCTModule/UARCTStorage.h, urbanairship-react-native/ios/UARCTModule/UARCTStorage.m, urbanairship-react-native/ios/UARCTModule/UARCTUtils.h, urbanairship-react-native/ios/UARCTModule/UARCTUtils.m, urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m, urbanairship-react-native/js/UrbanAirship.ts
Makes it possible to trigger takeOff from the react native clients.
Provides full control over takeOff and makes it easier to integrate into expo managed work flows.
Tested sample app, verified event listeners, features, takeOff, etc..
=> [MOBILE-2963] Add takeOff and isFlying

urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
Fixes getSubscriptionLists on Android. It was missing breaks in the switch and only parsed the first type from the param list.
=> [GH-390] Fix getSubscriptionLists on Android

urbanairship-react-native/ios/UARCTModule/UARCTAirshipListener.h, urbanairship-react-native/ios/UARCTModule/UARCTAirshipListener.m, urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m
Fix an issue with event not triggered in iOS.
Testing manually with sample app.
=> Fix an issue with events not triggered

CHANGELOG.md, example/ios/Podfile.lock, urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m, urbanairship-accengage-react-native/package.json, urbanairship-chat-react-native/package.json, urbanairship-hms-react-native/package.json, urbanairship-preference-center-react-native/package.json, urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m, urbanairship-react-native/package.json
=> Release 14.2.1

CHANGELOG.md, example/ios/Podfile.lock, urbanairship-accengage-react-native/android/build.gradle, urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m, urbanairship-accengage-react-native/package.json, urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec, urbanairship-chat-react-native/android/build.gradle, urbanairship-chat-react-native/package.json, urbanairship-chat-react-native/urbanairship-chat-react-native.podspec, urbanairship-hms-react-native/android/build.gradle, urbanairship-hms-react-native/package.json, urbanairship-preference-center-react-native/android/build.gradle, urbanairship-preference-center-react-native/package.json, urbanairship-preference-center-react-native/urbanairship-preference-center-react-native.podspec, urbanairship-react-native/android/build.gradle, urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m, urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m, urbanairship-react-native/package.json, urbanairship-react-native/urbanairship-react-native.podspec
- Updated iOS SDK to 16.8.0
- Updated Android SDK to 16.6.1
Using sample app
=> Update latest SDK

.github/workflows/ci.yml, CHANGELOG.md, example/android/build.gradle, example/ios/AirshipSample.xcodeproj/project.pbxproj, example/ios/Podfile.lock, urbanairship-accengage-react-native/android/build.gradle, urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m, urbanairship-accengage-react-native/package.json, urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec, urbanairship-chat-react-native/android/build.gradle, urbanairship-chat-react-native/package.json, urbanairship-chat-react-native/urbanairship-chat-react-native.podspec, urbanairship-hms-react-native/android/build.gradle, urbanairship-hms-react-native/package.json, urbanairship-preference-center-react-native/android/build.gradle, urbanairship-preference-center-react-native/package.json, urbanairship-preference-center-react-native/urbanairship-preference-center-react-native.podspec, urbanairship-react-native/android/build.gradle, urbanairship-react-native/ios/UARCTModule/UARCTAirshipListener.m, urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m, urbanairship-react-native/package.json, urbanairship-react-native/urbanairship-react-native.podspec
Update SDK versions
Keep our framework updated
Build and run
=> MOBILE-3251] Release 14.4.3

CHANGELOG.md, example/ios/Podfile.lock, urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m, urbanairship-accengage-react-native/package.json, urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec, urbanairship-chat-react-native/package.json, urbanairship-chat-react-native/urbanairship-chat-react-native.podspec, urbanairship-hms-react-native/package.json, urbanairship-preference-center-react-native/package.json, urbanairship-preference-center-react-native/urbanairship-preference-center-react-native.podspec, urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.java, urbanairship-react-native/ios/UARCTModule/UARCTAutopilot.m, urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m, urbanairship-react-native/js/UrbanAirship.ts, urbanairship-react-native/package.json, urbanairship-react-native/urbanairship-react-native.podspec
prepare release 14.6.0
- Updated iOS SDK to 16.10.6
- Add support for isChannelCaptureEnabled and suppressAllowListError.
Sample app
=> Release 14.6.0

urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/ReactNotificationProvider.java, urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java
Update the ReactNotificationProvider to extend the notification builder with the push message in the extras
To fix the getActiveNotifications method
Manual test
=> [MOBILE-3441] fix getActiveNotifications method

CHANGELOG.md, example/ios/Podfile.lock, urbanairship-accengage-react-native/ios/AirshipAccengageReactModuleVersion.m, urbanairship-accengage-react-native/package.json, urbanairship-accengage-react-native/urbanairship-accengage-react-native.podspec, urbanairship-chat-react-native/package.json, urbanairship-chat-react-native/urbanairship-chat-react-native.podspec, urbanairship-hms-react-native/package.json, urbanairship-preference-center-react-native/package.json, urbanairship-preference-center-react-native/urbanairship-preference-center-react-native.podspec, urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/UrbanAirshipReactModule.java, urbanairship-react-native/ios/UARCTModule/UARCTModuleVersion.m, urbanairship-react-native/package.json, urbanairship-react-native/urbanairship-react-native.podspec
Prepare release 14.6.1
Bump iOS SDK to 16.10.7
Add promise.resolve() to android enableFeature, disableFeature and setEnabledFeatures
=> prepare release 14.6.1

CHANGELOG.md, android/gradle.properties, android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt, example/ios/Podfile.lock, ios/AirshipReactNative.swift, package.json, react-native-airship.podspec, src/AirshipAnalytics.ts, src/types.ts
Real minor release, mostly a bug fix for trackScreen
=> Release 15.1.0

.github/workflows/ci.yml, .github/workflows/release.yml, CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, ios/AirshipReactNative.swift, package.json
Still need to verify older versions. Taken from the bob builder template before they removed it.
=> Release 15.1.1

CHANGELOG.md, ios/AirshipReactNative.swift, package.json
Patch release that adds missing annotation on feature flag methods  `featureFlagManagerFlag` and `featureFlagManagerTrackInteraction` and updates the Android and iOS example apps.
=> Release 17.1.1

package-lock.json, package.json
Uses the build tsconfig that excludes the example directory for docs
=> Fix docs build

example/ios/AirshipExample.xcodeproj/project.pbxproj, example/ios/AirshipExampleNotificationServiceExtension/Info.plist, example/ios/AirshipExampleNotificationServiceExtension/NotificationService.swift, example/ios/Podfile, example/ios/Podfile.lock
Adds a service extension to the sample
=> Add service extension

CHANGELOG.md, android/gradle.properties, example/ios/Podfile.lock, ios/AirshipReactNative.swift, package.json, react-native-airship.podspec
=> Release 18.0.4

CHANGELOG.md, android/gradle.properties, example/ios/Podfile.lock, ios/AirshipReactNative.swift, package.json, react-native-airship.podspec
=> Release 18.0.5

ios/RTNAirshipMessageView.mm
We at [Software Mansion](https://swmansion.com/) have been working on [improving support](https://blog.swmansion.com/sunrising-new-architecture-in-the-new-expensify-app-729d237a02f5) for the new architecture for quite a while now. If you need help with anything related to New Architecture, like:
- [migrating your library](https://x.com/swmansion/status/1717512089323864275)
- [migrating your app](https://github.com/Expensify/App/pull/13767)
- [investigating issues](https://github.com/facebook/react-native/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Aj-piasecki+is%3Aopen)
- [improving performance](https://x.com/BBloniarz_/status/1808138585528303977)
or you just want to ask any questions, hit us up on [projects@swmansion.com](mailto:projects@swmansion.com)
---
PR adding `load` method needed …
=> feat: add load method

android/src/main/AndroidManifest.xml, android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt, ios/AirshipReactNative.swift, ios/RTNAirship.mm, src/AirshipMessageCenter.ts, src/NativeRTNAirship.ts
Adds showMessageCenter and showMessageView
=> Add show message center methods

CHANGELOG.md, android/gradle.properties, example/ios/Podfile.lock, ios/AirshipReactNative.swift, package.json, react-native-airship.podspec
Fixes: https://github.com/urbanairship/react-native-airship/issues/605
=> Release 20.0.1

CHANGELOG.md, android/gradle.properties, example/ios/Podfile.lock, ios/AirshipReactNative.swift, package.json, react-native-airship.podspec
=> Release 20.0.4

.github/workflows/ci.yml, android/gradle.properties, android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt, android/src/main/java/com/urbanairship/reactnative/ReactAutopilot.kt, android/src/main/java/com/urbanairship/reactnative/ReactMessageView.kt, android/src/main/java/com/urbanairship/reactnative/ReactNotificationProvider.kt, example/ios/AirshipExample.xcodeproj/project.pbxproj, example/ios/ExampleWidgets/ExampleWidgetsLiveActivity.swift, example/ios/Podfile, example/ios/Podfile.lock, ios/AirshipReactNative.swift, ios/MessageWebViewWrapper.swift, ios/ProxyDataMigrator.swift, ios/RTNAirship.mm, package.json, react-native-airship.podspec
=> Update to SDK 19

CHANGELOG.md, android/gradle.properties, example/ios/AirshipExample.xcodeproj/project.pbxproj, example/ios/Podfile.lock, ios/AirshipReactNative.swift, package.json, react-native-airship.podspec
=> Release 22.1.0

CHANGELOG.md, android/gradle.properties, android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt, android/src/oldarch/java/com/urbanairship/reactnative/AirshipSpec.kt, example/ios/Podfile.lock, example/react-native.config.js, ios/AirshipReactNative.swift, ios/RNAirship.mm, package-lock.json, package.json, react-native-airship.podspec, src/AirshipChannel.ts, src/AttributeEditor.ts, src/NativeRNAirship.ts
Same as 24.1 but for the 23.x branch
=> Release 23.2.0

CHANGELOG.md, android/gradle.properties, android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt, android/src/oldarch/java/com/urbanairship/reactnative/AirshipSpec.kt, example/ios/Podfile.lock, ios/AirshipReactNative.swift, ios/RTNAirship.mm, package-lock.json, package.json, react-native-airship.podspec, src/AirshipChannel.ts, src/AttributeEditor.ts, src/NativeRTNAirship.ts
Hopefully last release for the 21.x branch
=> Release 21.5.0

CHANGELOG.md, android/gradle.properties, ios/AirshipReactNative.swift, package-lock.json, package.json, react-native-airship.podspec, scripts/update_changelog.sh
=> Release 24.7.0

CHANGELOG.md, android/gradle.properties, ios/AirshipReactNative.swift, package.json, react-native-airship.podspec
=> Release 24.8.0
